package webElements;

public class WebelementsForSmallBusinessVideo {
    public static final String homeTabElement="SMB_VH_Homepage_Home";
    public static final String mostPopularTabElement="SMB_VH_Homepage_MostPop";
    public static final String cashManagementTabElement="SMB_VH_Homepage_CashMgmt";
    public static final String bankingServicesTabElement ="SMB_VH_Homepage_Banking";
    public static final String payrollServicesTabElement= "SMB_VH_Homepage_Payroll";
    public static final String resourcesTabElement ="SMB_VH_Homepage_Resources";
    public static final String retirementTabElement="SMB_VH_Homepage_Retirement";
    public static final String creditTabElement="SMB_VH_Homepage_Credit";
    public static final String businessAdvantageRelationshipRewardTab="SMB_VH_Homepage_BARR";
    public static final String businessCardBasicsElement ="a[id='SMB_VH_CardRewards_CP_SubCardBasics']";
    public static final String accountManagementElement =   "SMB_VH_CardRewards_CP_SubAcctMgmt";
    public static final String CreditCardReward= "SMB_VH_CardRewards_CP_SubCardRewards";
    public static final String privateBankElement="//a[@class='t-track-teaser-cta cta__anchor cta__anchor--buttonbase  t-track-teaser-cta ']";
    public static final String merrilLearnMoreElement="//a[@class='t-track-teaser-cta cta__anchor cta__anchor--buttonbase  t-track-teaser-cta ']";
    public static final String merrilLearnMore2Element= "//a[@class='t-track-teaser-cta cta__anchor cta__anchor--buttonbase  t-track-teaser-cta ']";
    public static final String url="https://www.merrill.com/";
    public static final String privateBank2Element = "//a[@class='t-track-teaser-cta cta__anchor cta__anchor--buttonbase  t-track-teaser-cta ']";
    public static final String OnlineIDWebElements = "#onlineId1";
    public static final String passcodeWebElement = "#passcode1";
    public static final String saveOnlineIdWebElement = "#saveOnlineId";
    public static final String seeOptionsWebElement = " span[class='spa-btn spa-btn--primary spa-btn--medium masthead-cta-btn']";
    public static final String openNowWebElement = " span[class='spa-btn spa-btn--primary spa-btn--medium masthead-cta-btn']";
    public static final String radioButtonWebElement = " //*[@id=\"rb-savings-account-none\"]";
    public static final String DynamicheckBoxWebElement = "input[type='checkbox']";
    public static final String DropButton = "  #HomeLoans_GetStarted_2017mOAA2RS";
    public static final String url1 = "https://www.bankofamerica.com/deposits/checking/advantage-safebalance-banking-account/before-you-apply/";
    public static final String boaUrl = "https://www.bankofamerica.com/";
    public static final String cignaUrl = "https://www.cigna.com/";
    public static final String At_tUrl = "https://www.att.com/";
    public static final String buttonWebelement = "//*[@id=\"featured\"]/div/div[2]/div[5]/div/ul/li[3]/a";
    public static final String clickelement = "#socialShare > div > a";
    public static final String url3   = "https://www.bofaml.com/content/boaml/en_us/home.html";
    public static final String inputbox="a[class='close-top-nav menu-icon menu-icon--htx']";
    public static final String inputSearchbox="#nav-search-query";
    public static final String buttonelement="#headerMenuContainer > div > div.search.row.collapse.full-width-row > div > div > div > form > div.search-input-container.cf > input.submit.track-me";
    public static final String bankurl=  "https://www.bankofamerica.com/";
    public static final String checkingtab= " #bmhCarousel > div > div:nth-child(4) > li";
    public static final String url4= "https://promo.bankofamerica.com/small-business-videos/";
}
