package webElements;

public class WebElementsForBoA {
    public static final String OnlineIDWebElements = "#onlineId1";
    public static final String passcodeWebElement = "#passcode1";
    public static final String saveOnlineIdWebElement = "#saveOnlineId";
    public static final String seeOptionsWebElement = " span[class='spa-btn spa-btn--primary spa-btn--medium masthead-cta-btn']";
    public static final String openNowWebElement = " span[class='spa-btn spa-btn--primary spa-btn--medium masthead-cta-btn']";
    public static final String radioButtonWebElement = " //*[@id=\"rb-savings-account-none\"]";
    public static final String DynamicheckBoxWebElement = "input[type='checkbox']";
    public static final String DropButton = "  #HomeLoans_GetStarted_2017mOAA2RS";
    public static final String url1 = "https://www.bankofamerica.com/deposits/checking/advantage-safebalance-banking-account/before-you-apply/";
    public static final String boaUrl = "https://www.bankofamerica.com/";
    public static final String cignaUrl = "https://www.cigna.com/";
    public static final String At_tUrl = "https://www.att.com/";
    public static final String buttonWebelement = "//*[@id=\"featured\"]/div/div[2]/div[5]/div/ul/li[3]/a";
    public static final String clickelement = "#socialShare > div > a";
    public static final String url3 = "https://www.bofaml.com/content/boaml/en_us/home.html";
    public static final String openCheckingAcElement=  "span.spa-btn";
    public static final String getMostFromYourCheckingCreditCardElement ="/html/body/div[1]/div/div/section[3]/div/div/div[2]/div[2]/div/ul/li[1]/a/p";
    public static final String ourVideosCanHelpYouRunElement="/html/body/div[1]/div/div/section[3]/div/div/div[2]/div[2]/div/ul/li[2]/a/p";
    public static final String bestPracticesForProcessingPayrollElement="/html/body/div[1]/div/div/section[3]/div/div/div[2]/div[2]/div/ul/li[3]/a/p";
    public static final String needFinancingFindTheRightSolutionElement="/html/body/div[1]/div/div/section[3]/div/div/div[2]/div[2]/div/ul/li[4]/a/p";
    public static final String meetBusinessAdvantage360Element= "#yniMeetBusinessAdvantage360Cta";
    public static final String signGoPaperLessElement= "//a[@id='sign-in' and @class='spa-btn spa-btn--primary spa-btn--medium']";
    public static final String onlineBankingServiceAgreementElement="footer_bofa_online_banking_service_agreement";
    public static final String checkingHiddenMenuElement="#navCheckingContent > div:nth-child(2)";
    public static final String betterMoneyHabitsHiddenMenuElement ="#navBetterMoneyHabitsContent > div:nth-child(2)";
    public static final String checkingElement="navChecking";
    public static final String savingElement ="navSavings";
    public static final String savingHiddenMenuElement="#navSavingsContent > div:nth-child(2) > div:nth-child(1)";
    public static final String creditCardsHiddenMenuElement="#navCreditCardsContent";
    public static final String betterMoneyHabitsElement="Better Money Habits®";
    public static final String creditCardsElement = "navCreditCards";
    public static final String homeLoansElement="Home Loans";
    public static final String investingHiddenMenuElement="#navInvestingContent > div:nth-child(2)";
    public static final String homeLoansHiddenMenuElement ="#navHomeLoansContent";
    public static final String autoLoansElement="#navAutoLoans";
    public static final String investingElement="#navInvesting";
    public static final String autoLoansHiddenMenuElement="#navAutoLoansContent > div:nth-child(2) > div:nth-child(1)";
    public static final String accessibleBankingFooterElement="//*[@id=footer_bofa_careers]";
    public static final String carrearsFooterElement="footer_bofa_careers";
    public static final String personalElement="NAV_PERSONAL";
    public static final String privacySecurityFooterElement="footer_bofa_privacy_and_security";
    public static final String wealthManagemetElement = "#NAV_WEALTH_MANAGEMENT";
    public static final String smallBusinessElement= "#NAV_BUSINESS_ADVANTAGE";
    public static final String businessInstitutionElement =  "#NAV_BUSINESS_INSTITUTIONS";
    public static final String securityElement = "NAV_SECURITY";
    public static final String aboutUsElement=   "About Us";
    public static final String enEspanolElement = "#NAV_EN_ES";
    public static final String contactUsElement= "#NAV_CONTACT_US";
    public static final String helpnElement ="#NAV_HELP";
    public static final String helpSearchButtonElement= ".submit";
    public static final String helpSearchBarElement = "//input[@id='nav-search-query' and @class='search-query']";
    public static final String viewAllSearchElement= "//a[@class='track-me' and @name='Search Module - Top Result - See More Search Results']";
    public static final String popUpHelpSuggestionsElement=  ".search-form";
    public static final String feedbackElement=  ".feedback > a:nth-child(1)";
    public static final String locationFooterElement= "Locations";
    public static final String contactUsFooterElement ="Contact Us";
    public static final String helpFooterElement= "Help";
    public static final String mcafeeFooterElement= "#footer_bofa_mcafee_internet_security";
    public static final String sitemapFooterElement = "footer_bofa_sitemap";
    public static final String feedbackFooterElement = "//a[@id='footer_bofa_feedback']";
    public static final String advertisingPracticeFooterElement = "Advertising Practices";
    public static final String followFacebookElement ="/html/body/div[1]/div[1]/div/section[5]/div/div/div/footer/div[2]/div/div/div/div[2]/div/div/div/div[1]/a[1]/svg";
    public static final String nlineBankingLinkrElement= "#footer_bofa_view_full_online_banking_site";
    public static final String followInstagramElement = "social_follow_instagram_link";
    public static final String followPinterestElement ="social_follow_pinterest_link";
    public static final String followLinkedinElement = "social_follow_linkedin_link";
    public static final String followTwitterElement = "//a[@id=social_follow_twitter_link]";
    public static final String followYoutubeElement = "social_follow_youtube_link";
    public static final String equalHousingElement =  ".equalhousing-container";
    public static final String locatorboa = "#stateModalContent > h3:nth-child(1)";
    public static final String homeTabElement="SMB_VH_Homepage_Home";
    public static final String mostPopularTabElement="SMB_VH_Homepage_MostPop";
    public static final String cashManagementTabElement="SMB_VH_Homepage_CashMgmt";
    public static final String bankingServicesTabElement ="SMB_VH_Homepage_Banking";
    public static final String payrollServicesTabElement= "SMB_VH_Homepage_Payroll";
    public static final String resourcesTabElement ="SMB_VH_Homepage_Resources";
    public static final String retirementTabElement="SMB_VH_Homepage_Retirement";
    public static final String creditTabElement="SMB_VH_Homepage_Credit";
    public static final String businessAdvantageRelationshipRewardTab="SMB_VH_Homepage_BARR";
    public static final String businessCardBasicsElement ="a[id='SMB_VH_CardRewards_CP_SubCardBasics']";
    public static final String accountManagementElement =   "SMB_VH_CardRewards_CP_SubAcctMgmt";
    public static final String CreditCardReward= "SMB_VH_CardRewards_CP_SubCardRewards";
    public static final String privateBankElement="//a[@class='t-track-teaser-cta cta__anchor cta__anchor--buttonbase  t-track-teaser-cta ']";
    public static final String merrilLearnMoreElement="//a[@class='t-track-teaser-cta cta__anchor cta__anchor--buttonbase  t-track-teaser-cta ']";
    public static final String merrilLearnMore2Element= "//a[@class='t-track-teaser-cta cta__anchor cta__anchor--buttonbase  t-track-teaser-cta ']";
    public static final String url="https://www.merrill.com/";
}
