package webElements;

public class WebElementsForBoA {
    public static final String OnlineIDWebElements = "#onlineId1";
    public static final String passcodeWebElement = "#passcode1";
    public static final String saveOnlineIdWebElement = "#saveOnlineId";
    public static final String checkingHiddenMenuElement="#navCheckingContent > div:nth-child(2)";
    public static final String betterMoneyHabitsHiddenMenuElement ="#navBetterMoneyHabitsContent > div:nth-child(2)";
    public static final String checkingElement="navChecking";
    public static final String savingElement ="navSavings";
    public static final String savingHiddenMenuElement="#navSavingsContent > div:nth-child(2) > div:nth-child(1)";
    public static final String creditCardsHiddenMenuElement="#navCreditCardsContent";
    public static final String betterMoneyHabitsElement="Better Money Habits®";
    public static final String creditCardsElement = "navCreditCards";
    public static final String homeLoansElement="Home Loans";
    public static final String investingHiddenMenuElement="#navInvestingContent > div:nth-child(2)";
    public static final String homeLoansHiddenMenuElement ="#navHomeLoansContent";
    public static final String autoLoansElement="#navAutoLoans";
    public static final String investingElement="#navInvesting";
    public static final String autoLoansHiddenMenuElement="#navAutoLoansContent > div:nth-child(2) > div:nth-child(1)";
    public static final String accessibleBankingFooterElement="//*[@id=footer_bofa_careers]";
    public static final String carrearsFooterElement="footer_bofa_careers";
    public static final String personalElement="NAV_PERSONAL";
    public static final String privacySecurityFooterElement="footer_bofa_privacy_and_security";
    public static final String wealthManagemetElement = "#NAV_WEALTH_MANAGEMENT";
    public static final String smallBusinessElement= "#NAV_BUSINESS_ADVANTAGE";
    public static final String businessInstitutionElement =  "#NAV_BUSINESS_INSTITUTIONS";
    public static final String securityElement = "NAV_SECURITY";
    public static final String aboutUsElement=   "About Us";
    public static final String enEspanolElement = "#NAV_EN_ES";
    public static final String contactUsElement= "#NAV_CONTACT_US";
    public static final String helpnElement ="#NAV_HELP";
    public static final String helpSearchButtonElement= ".submit";
    public static final String helpSearchBarElement = "//input[@id='nav-search-query' and @class='search-query']";
    public static final String viewAllSearchElement= "//a[@class='track-me' and @name='Search Module - Top Result - See More Search Results']";
    public static final String popUpHelpSuggestionsElement=  ".search-form";
    public static final String feedbackElement=  ".feedback > a:nth-child(1)";
    public static final String locationFooterElement= "Locations";
    public static final String contactUsFooterElement ="Contact Us";
    public static final String helpFooterElement= "Help";
    public static final String mcafeeFooterElement= "#footer_bofa_mcafee_internet_security";
    public static final String sitemapFooterElement = "footer_bofa_sitemap";
    public static final String feedbackFooterElement = "//a[@id='footer_bofa_feedback']";
    public static final String advertisingPracticeFooterElement = "Advertising Practices";
    public static final String followFacebookElement ="/html/body/div[1]/div[1]/div/section[5]/div/div/div/footer/div[2]/div/div/div/div[2]/div/div/div/div[1]/a[1]/svg";
    public static final String nlineBankingLinkrElement= "#footer_bofa_view_full_online_banking_site";
    public static final String followInstagramElement = "social_follow_instagram_link";
    public static final String followPinterestElement ="social_follow_pinterest_link";
    public static final String followLinkedinElement = "social_follow_linkedin_link";
    public static final String followTwitterElement = "//a[@id=social_follow_twitter_link]";
    public static final String followYoutubeElement = "social_follow_youtube_link";
    public static final String equalHousingElement =  ".equalhousing-container";
    public static final String locatorboa = "#stateModalContent > h3:nth-child(1)";
}
